#生产环境
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.152.80:3306/db_exam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: true  #开启缓存
  redis:
    host: 47.96.152.80
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms #连接池最阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲数
        min-idle: 0 #连接池中的最小空闲数

imgFilePath: D:/tmp/img
lucenePath: D:/tmp/lucene
